/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package christianmosci_progettoclienthttp;

import java.io.IOException;

/**
 *
 * @author mosci.christian
 */
public class Form1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form1.class.getName());
    private httpClient httpClient;

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etichetta1 = new javax.swing.JLabel();
        Etichetta2 = new javax.swing.JLabel();
        txt_InserisciUrl = new javax.swing.JTextField();
        cb_Comandi = new javax.swing.JComboBox<>();
        Etichetta3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txa_Richiesta = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txa_Risposta = new javax.swing.JTextArea();
        Etichetta4 = new javax.swing.JLabel();
        Btn_Invia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Etichetta1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Etichetta1.setText("Client Http");
        getContentPane().add(Etichetta1);
        Etichetta1.setBounds(220, 10, 130, 45);

        Etichetta2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Etichetta2.setText("Risposta dal Server:");
        getContentPane().add(Etichetta2);
        Etichetta2.setBounds(10, 360, 180, 25);
        getContentPane().add(txt_InserisciUrl);
        txt_InserisciUrl.setBounds(170, 70, 190, 50);

        cb_Comandi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Get", "Head" }));
        getContentPane().add(cb_Comandi);
        cb_Comandi.setBounds(410, 70, 100, 50);

        Etichetta3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Etichetta3.setText("Url Richiesta:");
        getContentPane().add(Etichetta3);
        Etichetta3.setBounds(30, 80, 120, 25);

        jScrollPane1.setViewportView(Txa_Richiesta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 170, 290, 160);

        Txa_Risposta.setColumns(20);
        Txa_Risposta.setRows(5);
        jScrollPane2.setViewportView(Txa_Risposta);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 360, 290, 150);

        Etichetta4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Etichetta4.setText("Richiesta inviata:");
        getContentPane().add(Etichetta4);
        Etichetta4.setBounds(20, 170, 150, 25);

        Btn_Invia.setText("Invia Richiesta");
        Btn_Invia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InviaActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Invia);
        Btn_Invia.setBounds(190, 530, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_InviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InviaActionPerformed
        // Bottone Invia Richiesta
             try {
            // Leggo i dati dalla form
            String host = txt_InserisciUrl.getText().trim(); 
            String comando = cb_Comandi.getSelectedItem().toString();
            int porta = 80; // setto la porta del http

            // Creo l’oggetto con l'host e porta
            httpClient = new httpClient(null, null, null, host, porta);

            // richiesta
            String richiesta = comando + " / HTTP/1.1\r\n" +
                               "Host: " + host + "\r\n" +
                               "User-Agent: JavaHttpClient/1.0\r\n" +
                               "Connection: close\r\n\r\n";

            // Mostro la richiesta 
            Txa_Richiesta.setText(richiesta);

            // Eseguo la richiesta
            String risposta = httpClient.eseguiRichiesta(comando, "/");

            // Mostro la risposta
            Txa_Risposta.setText(risposta);

            javax.swing.JOptionPane.showMessageDialog(this, "Richiesta inviata");
        } catch (IOException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Errore! " + ex.getMessage());
        }
        
    }//GEN-LAST:event_Btn_InviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Invia;
    private javax.swing.JLabel Etichetta1;
    private javax.swing.JLabel Etichetta2;
    private javax.swing.JLabel Etichetta3;
    private javax.swing.JLabel Etichetta4;
    private javax.swing.JTextPane Txa_Richiesta;
    private javax.swing.JTextArea Txa_Risposta;
    private javax.swing.JComboBox<String> cb_Comandi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_InserisciUrl;
    // End of variables declaration//GEN-END:variables
}
